### ISSUE TITLE
Adopt a package manager

### ISSUE THREAD

**Issue by vwxyzjn** [NREL/graph-env#33]
Hi @pstjohn, this is a cool project! 

Have you considered adopting a package manager like [poetry](https://python-poetry.org/)? The current way of installing with `setup.py` is deprecated by PyPa (see https://pip.pypa.io/en/stable/reference/build-system/setup-py/#setup-py-legacy). For future projects, PyPa recommends using `pyproject.toml`, which can be automatically generated by `poetry`. Poetry also has many benefits, like locking the dependencies to ensure reproducibility — an important consideration for research projects.

Feel free to checkout how we use poetry in CleanRL ([docs](https://docs.cleanrl.dev/get-started/installation/) and [pyproject.toml](https://github.com/vwxyzjn/cleanrl/blob/master/pyproject.toml)).

**Comment by vwxyzjn** [comment]
Thanks for entertaining with this. Yeah, it's a bit unfortunate that `ray` locking can take a long time. If it's too much pain, then https://github.com/NREL/graph-env/pull/35 looks good to me. 

Feel free to close this.

As a side note — have you considered supporting other DRL libraries like Stable-baselines3?

**Comment by pstjohn** [comment]
Stable baselines would definitely be neat to support. I think that would need to come in a later version of this package though, so I'll close this issue out and keep that on our development roadmap for the future. Thanks for the comments!
